"""add active field to verification code table

Revision ID: 067b03fb04e3
Revises: 6f3229bf1937
Create Date: 2020-11-25 06:23:39.895099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067b03fb04e3'
down_revision = '6f3229bf1937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
