"""add channel table

Revision ID: 4bba7593ce8e
Revises: d2f3d6010615
Create Date: 2020-12-25 11:34:21.721511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bba7593ce8e'
down_revision = 'd2f3d6010615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ctype', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel'))
    )
    op.create_table('channels',
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_channels_channel_id_channel'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_channels_user_id_user'), ondelete='CASCADE')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_message_channel_id_channel'), 'channel', ['channel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_channel_id_channel'), type_='foreignkey')
        batch_op.drop_column('channel_id')

    op.drop_table('channels')
    op.drop_table('channel')
    # ### end Alembic commands ###
