"""add verification code model

Revision ID: 6f3229bf1937
Revises: ee1a61f26c5e
Create Date: 2020-11-25 05:22:23.004286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3229bf1937'
down_revision = 'ee1a61f26c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('vcode', sa.String(length=6), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('vtype', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_code'))
    )
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_code_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_code_vcode'), ['vcode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_code_vcode'))
        batch_op.drop_index(batch_op.f('ix_verification_code_email'))

    op.drop_table('verification_code')
    # ### end Alembic commands ###
