"""fix tags

Revision ID: 9a23442e6dc7
Revises: ebc647f3e4e4
Create Date: 2020-12-04 11:28:54.525352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a23442e6dc7'
down_revision = 'ebc647f3e4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tags_tag_id_tag', type_='foreignkey')
        batch_op.drop_constraint('fk_tags_post_id_post', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tags_post_id_post'), 'post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_tags_tag_id_tag'), 'tag', ['tag_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tags_tag_id_tag'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tags_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tags_post_id_post', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('fk_tags_tag_id_tag', 'tag', ['tag_id'], ['id'])

    # ### end Alembic commands ###
