"""fix comment table

Revision ID: aab7504e7732
Revises: a942587c4d2c
Create Date: 2020-11-26 10:18:30.606134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab7504e7732'
down_revision = 'a942587c4d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index('ix_comment_email')
        batch_op.create_index(batch_op.f('ix_comment_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_email'))
        batch_op.create_index('ix_comment_email', ['email'], unique=1)

    # ### end Alembic commands ###
