"""fix claps table

Revision ID: ebc647f3e4e4
Revises: aab7504e7732
Create Date: 2020-11-27 08:02:52.834017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc647f3e4e4'
down_revision = 'aab7504e7732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_claps_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_claps_post_id_post', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_claps_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_claps_post_id_post'), 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_claps_post_id_post'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_claps_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_claps_post_id_post', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('fk_claps_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
