"""modify notification table

Revision ID: f88f293dff94
Revises: 8e3469def6ea
Create Date: 2020-12-22 17:14:04.085581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88f293dff94'
down_revision = '8e3469def6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('unread', sa.Boolean(), nullable=True))
        batch_op.drop_column('payload_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload_json', sa.TEXT(), nullable=True))
        batch_op.drop_column('unread')
        batch_op.drop_column('body')

    # ### end Alembic commands ###
