"""modify message table

Revision ID: fbb3ebcf5f90
Revises: f88f293dff94
Create Date: 2020-12-24 11:08:08.957481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb3ebcf5f90'
down_revision = 'f88f293dff94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mtype', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('mtype')

    # ### end Alembic commands ###
